### ISSUE TITLE
Repeat a single track

### ISSUE THREAD

**Issue by shreyasminocha** [kraxarn/spotify-qt#108]
Unless I'm mistaken, the "Repeat" button repeats a playlist, album, or library. I'd love to be able to repeat a single track though. The official spotify apps implement this in the form of a toggle between three states: no loop, loop playlist (?), and loop track.

**Comment by kraxarn** [comment]
There is some support for it, as it can handle it being changed from other clients, there's just no way to change it from the UI itself.

**Comment by lf-** [comment]
Based on some experiments involving patching spotify-qt to just use track repeat instead of context repeat, I am unsure if this works for spotifyd for reasons independent of the UI:

* Trying to set spotifyd to repeat one track, with the web ui, did not succeed, and only allowed either no repeat or repeating the list
* Patching spotify-qt to set the repeat state to track instead of context, and printing some debug output indicates that we asked the spotify API to set the repeat state to track and it decided it was not interested and instead set it to context in the next refresh response..... I don't get it.
* If I, instead of playing on spotifyd, play on the spotify web client, then it *is* possible to set it to track mode both on that web client and in my modified spotify-qt interface

My speculation is that this is not a spotifyd bug and is instead a limitation of third party spotify players, but it perhaps could be. I shall go look at its code.

**Comment by kraxarn** [comment]
Just did some quick testing and seems to work fine. Only thing I noted was that after the track has been repeated once, it goes back to repeating the entire list. Quite odd, as the official client seem to continue repeating the track, but also seems to be a bit too specific to be a bug, so maybe it's a feature, who knows.
