### ISSUE TITLE
Blurry Interface on HiDPI screen

### ISSUE THREAD

**Issue by andynameistaken** [kraxarn/spotify-qt#123]
![Screenshot 2021-09-04 at 16 04 38](https://user-images.githubusercontent.com/15692002/132097203-5587d19e-d983-41cf-928f-886a5ae6b080.png)
### System information

* MacBook Pro (16-inch, 2019)
* macOS Catalina 10.15.7 (19H1323)
### Detailed information
Program does not scale well on HiDPI screen, it is blurry:

**Comment by kraxarn** [comment]
High DPI should be fully supported since #51, but from a quick read on the [Qt documentation](https://doc.qt.io/qt-5/highdpi.html#macos-and-ios), it seems a proper application bundle with a plist file is required for it to work properly. Maybe it's worth looking into making CMake generate a proper application bundle.
