### ISSUE TITLE
Says Premium Required. 

### ISSUE THREAD

**Issue by pakosaan** [kraxarn/spotify-qt#191]
Can't it be played with free account or is it exclusive to premium only ???

**Comment by RedwineOS** [comment]
As with most other third party clients, it is necessary to have a premium account due to limitations with the Spotify API.

Sadly, taking as reference [the ArchWiki entry](https://wiki.archlinux.org/title/spotify#Third-party_clients), there is no other major client that allows free tier accounts to use them.

**Comment by imhemish** [comment]
This issue should be closed as it is out of scope, due to limitations of spotify api.

**Comment by kraxarn** [comment]
From the readme:
> Note: Controlling playback requires Spotify Premium.

Unfortunately nothing I can do about.
