### ISSUE TITLE
MPRIS D-Bus Interface is buggy

### ISSUE THREAD

**Issue by kraxarn** [kraxarn/spotify-qt#4]
Due to the poor implementation of the MPRIS D-Bus interface, media controlling is buggy and manual D-Bus commands (or something like [playerctl](https://github.com/altdesktop/playerctl)) are needed to control the player.

Seems to be KDE specific. They also have a "proposed" MPRIS 3 specification that can be found [here](https://community.kde.org/MPRIS), but it doesn't seem to affect anything.

Scrap the Qt implementation and just use a common (glib based?) implementation instead, so it can be used with other user interfaces as well. Could be based on [other](https://github.com/Serranya/deadbeef-mpris2-plugin) [implementations](https://github.com/cmus/cmus/blob/master/mpris.c) for example.

**Comment by AryToNeX** [comment]
`xesam:album` should only ever be a string, however this project sets it to be a data structure containing the album name with key `name` and the album's spotify identifier with key `id`. While this is not wrong per se, it is surely not compliant with the current MPRIS specification, and as such some media controllers will get confused over it.

**Comment by kraxarn** [comment]
Nice catch! Fixed in ee43736a21c699779d59aba45a8cd52267ca9254. Unfortunately, it doesn't seem to have fixed anything though.

**Comment by AryToNeX** [comment]
On file 'src/mediaplayer/mediaplayer.cpp' there are some fields missing, most notably the 'DesktopEntry' one. I guess that is why the player will not show up on the KDE tray icon.

**Comment by AryToNeX** [comment]
Other stuff I found

- https://github.com/kraxarn/spotify-qt/blob/4180f3b98973db346fe464a3ff57236037f846f0/src/mediaplayer/mediaplayerplayer.cpp#L167

  You should only emit the `Seeked` event if the user did actually seek through the track on the spotify-qt window; otherwise you should only just update the `Position` property.
- On the same file, the LoopStatus property is missing (though it is optional)
- On the same file, `Seek` and `SetPosition` behave the same, which is not how the specification wants them to behave. `SetPosition` is correct, but `Seek` accepts an `offset` value and it should be treated as such (so `Seek(offset)` -> `SetPosition(currentPosition + offset)`

**Comment by kraxarn** [comment]
Because of #178, as well as some various commits after, I would now consider this stable enough to close this issue. The glib version will have to be reconsidered once a GTK-based frontend is available.
