### ISSUE TITLE
Library issue

### ISSUE THREAD

**Issue by Dulkien** [kraxarn/spotify-qt#5]
In the "Liked" is has just the last 20 music added. And the music is not in the "classic view" (playlist). There is 20 "Albums" too, but here the view work. And "No results" for "Artists"
![image](https://user-images.githubusercontent.com/39432426/78840852-28b6a780-79fc-11ea-9bfe-f5dd3d51e157.png)

**Comment by kraxarn** [comment]
The reason it's only 20 songs is because it currently does not do any paging, mostly to not fill up the list too much and it's not in the normal track list as I tried to make it more consistent, but loading all tracks and showing it in the main track list is probably better.

From the [release notes](https://github.com/kraxarn/spotify-qt/releases/tag/v0.18), the top artists and tracks adds new authentication scopes, and as no proper handling for it has been implemented, because I don't plan on changing the scopes that often, you currently need to sign out and back in again.
