### ISSUE TITLE
Fix dark theme in stable

### ISSUE THREAD

**Issue by kippenjongen** [kraxarn/spotify-qt#61]
Currently, when I try to tick the dark theme checkbox in the stable branch (or v3.4) it segfaults. This only happens when it is still in light theme, and in a build of the master branch this doesn't happen. Deselecting the dark theme when it has been set in a build of the master branch (where it doesn't segfault) also works, so it is really just the selecting that doesn't work in stable. Since this is already fixed, just not committed to a stable branch, I'm not sure if this is issue actually useful, but I couldn't see a previous issue about this so I thought it would be good to to make sure that its a known issue.

**Comment by kraxarn** [comment]
Fixed in fe916f8976cca3983030e24d02d65e62893ad88d and will be included in v3.5. I never considered it enough of an issue to fix in the stable branch, as that branch is designed to always match the latest release, but I guess including bug fixes like these in it as well wouldn't be a bad idea. The issue only affects systems without a system icon theme, so basically Windows and macOS.

**Comment by kippenjongen** [comment]
Ah ok, great! Would it maybe work to have a nightly branch or something where things like this can be pushed to that doesn't warrant a release on own, so that stable can stay just stay tracking the latest release? 
As for the icon theme, I thought that I had got one installed but I guess that it was missing whatever this needs or something, I probably deserve it for messing up my install as much as I have done...
