### ISSUE TITLE
does not detect raspotify nodes

### ISSUE THREAD

**Issue by pghpete** [kraxarn/spotify-qt#68]
I have various raspotify https://github.com/dtcooper/raspotify nodes around my house. Its great because I can use my phone and pick the playback node to play on.  It would be amazing if this application could "see" these devices.  I would love to help out in any way possible. logs, debug info, compiling code etc.

Please let me know if this may be available in the future and if so... can assist in anyway?

Thanks for a great project !

**Comment by pghpete** [comment]
Oddly, none of my nodes would show up until I brought up my phone app and started them that way.  As soon as I did they would appear in spotify-qt.  I am closing this. Thanks!!

**Comment by kraxarn** [comment]
The client currently only supports services you're signed in to. Other devices, which can be used from different accounts, without having to login, are currently not supported as they aren't available from the Spotify API, and would need to be managed separately, as they are only available locally. Because of that, there's currently no easy way to integrate it into the client, but once playback functionality is added, this is something I'll look into.
