### ISSUE TITLE
App crashes soon as I start

### ISSUE THREAD

**Issue by keshavbhatt** [kraxarn/spotify-qt#85]
### System information
The GUI is not opening, the app crash before it is even landed to the first window.

### Detailed information
I updated the latest version of the app from the snap store edge channel i.e, revision number 594. When i started the app it crashed with the following outout.
`[02:12:03  IST] [info] Last refresh was less than an hour ago, not refreshing access token
terminate called after throwing an instance of 'nlohmann::detail::parse_error'
  what():  [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal
Aborted (core dumped)
`

### What happens?
Application crashed. Aborted (core dumped).

### What should happen?
App should start properly.

**Comment by kraxarn** [comment]
Temporary workaround: start playback from another client and then start spotify-qt again and it should work.

**Comment by keshavbhatt** [comment]
When I start with a device already playing.
```
pure virtual method called
terminate called without an active exception
Aborted (core dumped)

```

**Comment by kraxarn** [comment]
It's another issue related to the initial access token refresh when starting the app, unrelated to if there's already a device selected or not. The only real workaround is to first start the stable version, and then the git version should start like normal after. If you run it from the snap, you can just temporarily switch to the stable channel, otherwise you can download the latest stable version from the [pre-built artifact](https://github.com/kraxarn/spotify-qt/suites/2238163716/artifacts/46440343), or just build it from the stable branch.

**Comment by keshavbhatt** [comment]
I was just reporting the issue i know i can switch to stable channel for stable working build :)

**Comment by kraxarn** [comment]
Maybe I should start using the beta/rc snap tags for stuff like this :thinking:

**Comment by keshavbhatt** [comment]
nah, nah edge mean unstable. 
everything is fine. I know what i was doing and was aware of results. Edge channel is for bleeding edge builds which may be unstable. I opened this issue so this could get fixed in next stable release.
